import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css']
})
export class DashboardComponent {
  fields = [
    { name: 'Patient Registration', options: ['Patient Details', 'All IDs'], selectedValue: '' },
    { name: 'Medical', options: ['Doctor Details', 'Medical History Documents'], selectedValue: '' },
    { name: 'Insurance', options: ['Policy', 'Company', 'Employer Company'], selectedValue: '' },
    { name: 'Consent', options: ['Form', 'Video - Patient', 'Video - Attendant', 'Written Signed Docs', 'Autogenerated Hospital Docs'], selectedValue: '' },
    { name: 'Police', options: ['Complaint', 'FIR', 'BAIL', 'Chargesheets', 'Court Resources', 'ORDERS', 'Litigation Status'], selectedValue: '' },
    { name: 'Court', options: ['Legal Notice', 'REPLY', 'Complaints', 'Objections', 'Court Records', 'Judgements', 'Litigation Status'], selectedValue: '' },
    { name: 'Laws Database', options: ['Acts + Rule', 'Judgements', 'Case Study', 'Drafts', 'Legal Advice'], selectedValue: '' },
    { name: 'Admin', options: ['(Internal)', '(External)'], selectedValue: '' },
    // {name: 'Admin ', options: [''], selectedValue: ''},
    { name: 'Tasks', options: ['(Internal)', '(External)'], selectedValue: '' },
    // {name: 'Tasks (External)', options: [''], selectedValue: ''},
  ];

  constructor(private router: Router) { }

  onSelectionChange(field: any) {
    if (field.selectedValue) {
      // Navigate to the route based on the selected value
      this.router.navigate([`/${field.selectedValue}`]);
    }
  }
}
